"""empty message

Revision ID: 97caa135a744
Revises: 
Create Date: 2022-10-13 12:47:00.101659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97caa135a744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('peer_coin', sa.String(), nullable=False),
    sa.Column('peer_coin_total_value', sa.Float(), nullable=False),
    sa.Column('type_value', sa.String(), nullable=False),
    sa.Column('usd_total_value', sa.Float(), nullable=False),
    sa.Column('usd_unit_price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('usd_fee', sa.Float(), nullable=False),
    sa.Column('coin_fee', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
